//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_OnlineQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string CodeMember { get; set; }
        public string Fullname { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Email { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
