//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_OnlineQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MixingExamDetail
    {
        public string CodeMixingExamDetail { get; set; }
        public Nullable<int> Num { get; set; }
        public string CodeMixingExam { get; set; }
        public string CodeExamDetail { get; set; }
    
        public virtual ExamDetail ExamDetail { get; set; }
        public virtual MixingExam MixingExam { get; set; }
    }
}
