//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_OnlineQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.ExamDetails = new HashSet<ExamDetail>();
        }
    
        public string CodeQuestion { get; set; }
        public string Text { get; set; }
        public string Image { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Difficulty { get; set; }
        public Nullable<int> NumOfIterations { get; set; }
        public string CodeSubject { get; set; }
        public string CodeTeacher { get; set; }
        public string CodeGeneralQuestion { get; set; }
        public string CodeChapter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Chapter Chapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamDetail> ExamDetails { get; set; }
        public virtual GeneralQuestion GeneralQuestion { get; set; }
        public virtual TeachingSubject TeachingSubject { get; set; }
    }
}
